### ISSUE TITLE
Landscape fix on hymn page

### ISSUE THREAD

**Issue by Emyeh** [HymnalDreamTeam/Hymns-iOS#135]
Everything looks really good on landscape except the hymn page:
1. It's too tight at the top, making it hard to tap on the left carat and favorite buttons. We need about a 16dp padding there.
2. The stanzas just need to be centered within the page (they can stay left aligned).

![IMG_7412](https://user-images.githubusercontent.com/26554065/81532243-ee9d3600-9318-11ea-9e78-f35f3a7f02c1.PNG)

@finben @skywalkerdude

**Comment by finben** [comment]
@Emyeh For the lyrics being centered. Is that only in landscape mode that they should be centered or does that also apply to vertical?

**Comment by Emyeh** [comment]
Let's apply it for both so we can have some consistency between the two views.
