### ISSUE TITLE
Huge gap whenever I install and open the app

### ISSUE THREAD

**Issue by Emyeh** [HymnalDreamTeam/Hymns-iOS#136]
Every time I install the test app a huge gap appears at the top. It eventually goes away after I come back to the app a few times. Using an iphone X.

![IMG_7415](https://user-images.githubusercontent.com/26554065/81533024-4c7e4d80-931a-11ea-8c54-e4a580cce5d7.PNG)

@finben @skywalkerdude

**Comment by skywalkerdude** [comment]
@Emyeh does this still happen for you

**Comment by Emyeh** [comment]
Nope looks like it's fixed for me

**Comment by rachely3n** [comment]
I'm not seeing it either
