### ISSUE TITLE
Fix .gitignore based on ikesyo's comment in https://github.com/HymnalDreamTeam/Hymns-iOS/pull/40#issuecomment-628811839_

### ISSUE THREAD

**Issue by skywalkerdude** [HymnalDreamTeam/Hymns-iOS#152]
The reason for the problem is https://github.com/Quick/Nimble/tree/8.x-branch/Carthage/Checkouts/CwlPreconditionTesting/Dependencies is ignored due to https://github.com/HymnalDreamTeam/Hymns-iOS/blob/f1363ad71ee2a9ce47dcbe34d3b372762fb6dbef/.gitignore#L69-L70. I recommend you to change the entry to `/Dependencies/`.

_Originally posted by @ikesyo in https://github.com/HymnalDreamTeam/Hymns-iOS/pull/40#issuecomment-628811839_

**Comment by ikesyo** [comment]
#66 should already resolved the issue.
