### ISSUE TITLE
7 Icons Question

### ISSUE THREAD

**Issue by finben** [HymnalDreamTeam/Hymns-iOS#170]
This is regarding the bottom toolbar when you are looking at a hymn. I just wanted to bring this up for consideration. To me the side tolerances look a little tight and 7 icons feels cluttered? Luke, mentioned the other android app also can have up to 7 but most hymns only have data for 6. What is your opinion? To me 6 icons seems to be the max amount that doesn't start feeling like too much. I wonder if we can move something like text size to our settings tab instead of having it right in the toolbar.

**Comment by Emyeh** [comment]
That's a good point, I agree it feels cluttered to have 6+ icons. We originally had all the icons there without considering a hierarchy of value, because we're not 100% sure which features people would use more or less. 

6 is a good amount to leave out for now. I think text size is a good one to put within an ellipses menu. I would assume people only need to adjust once. We have the ellipses for android, but I can also add it to the iOS designs.

**Comment by skywalkerdude** [comment]
@Emyeh I don't think we have ellipses on Android. We just show all 7 tabs (at most) if the hymn has everything. How should we ellipsize on Android?

**Comment by Emyeh** [comment]
I mean I have the ellipses in the android design already. I'll show the full flow for both.

**Comment by Emyeh** [comment]
@finben Added the ellipses menu to iOS and removed the font size icon from the hymn tool bar. Let me know if the custom bottom sheet will take too long, I can try to adjust to the standard iOS bottom sheet - https://www.figma.com/file/7H5ApjzuVuJL3OP7FvE2qe/h-app?node-id=647%3A3155

**Comment by finben** [comment]
@Emyeh Thanks, looks great!! Yeah, I am glad we are doing this. I went to test the app on my wife's small iPhone 7 and was trying to click one of the toolbar tabs and we both kept clicking the other one because they were so close together.

**Comment by Emyeh** [comment]
@finben Awesome! Let me think a little bit more about which features should also be included in the overflow menu. It looks a bit funny now with just the font size option. Will try to have something soon.

**Comment by skywalkerdude** [comment]
I think one of the key questions is: how do we show the overflow menu for the bottom bar?

Since we can have a dynamic number of tabs (anywhere from 3-7), I think the best would be that we prioritize them, and if there are too many, we put the lower priority tabs in an overflow menu.

But if that is the case, then that means the user will be used to going to the bottom of the screen for those options (since they will be there for other hymns). So the overflow option will need to be somewhere close to the bottom of the screen. The 3 dots on the top of the screen is a little far away from where the user would expect those options to be

**Comment by Emyeh** [comment]
That one option we can try. Although it's a common pattern for ellipses, It does seem disjointed to show a bottom sheet for both the features on the toolbar and the ellipses menu at the top. 

Some other options we can consider is to make the ellipses menu a dropdown. We can also try making it horizontally scrollable. Its not common but it works pretty well for apps that have a lot editing tools:
![ezgif com-optimize](https://user-images.githubusercontent.com/26554065/82787051-866f4980-9e1a-11ea-8895-8cff07bbb4c1.gif)

**Comment by finben** [comment]
What if we just move song info to the where the ellipsis currently is and bring text size back to the toolbar? I think it would make a lot of sense for two reasons. Firstly, because it is less of a tool and more just information so it would make the most sense not being in the toolbar. And second, its display is unlike all of the others in that it always just appears in the middle of the screen. 

By doing so we also avoid ever even having to move items to an overflow menu.

**Comment by finben** [comment]
One more thing lol... it also will match what our users are used to if they are accustomed to using hymnal.net on their phone before getting the app.

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-05-25 at 08 12 45](https://user-images.githubusercontent.com/15247726/82815846-9cebc400-9e5f-11ea-8318-14ca24b556cf.png)

**Comment by Emyeh** [comment]
Let me try out these suggestions on Figma. That way we can see which one feels better and get a sense what is more doable or doesn't require a ton of time to build.

**Comment by Emyeh** [comment]
I have 4 different explorations you can try out here: https://www.figma.com/proto/7H5ApjzuVuJL3OP7FvE2qe/h-app?node-id=1341%3A272&scaling=min-zoom

1. Bottom sheets
2. Dropdown
3. Toolbar setting icon
4. Horizontal scroll

For each exploration there's a different way you can interact with it, which I typed out on the first screen of each exploration. You can click or use the arrow keys to flip through all the screens. 

I'm leaning toward having the ellipses option within the toolbar or the horizontal scroll. It keeps the features within the same place while making the favorite at the top. The dropdown helps distinguish between the toolbar interactions and top ellipses, but it still looks a bit awkward to me. Also it's an older UI pattern, it seems like most apps use a bottom sheet.

**Comment by skywalkerdude** [comment]
Hmmm, I like the horizontal scroll. For the ellipses option, how come the dots are horizontal and not vertical? Would it look weird vertical?

**Comment by Emyeh** [comment]
The horizontal dots appears more visually balanced with the other icons. Without the visible width the vertical ellipses make it seems like there are bigger gaps surrounding it. It's also not typically used in ios apps.

**Comment by finben** [comment]
I like drop-down but with the info more in the middle like Luke has it now. I also am fine with horizontal scroll and the horizontal ellipsis. I think horizontal scroll is a bit wierd if there is only one additional option when you scroll. Like it would make more sense when you have more that you are scrolling too besides one extra.

**Comment by Emyeh** [comment]
That's a good point about the horizontal scroll. It's probably more beneficial if we have a lot more icons there. 

Then let's try out having an ellipses on the toolbar so that all the secondary hymn actions can remain at the bottom. We'll adjust it if we get any user feedback on it.

**Comment by finben** [comment]
I think we are done with this convo.
