### ISSUE TITLE
Hide "song info" if there is no info to show

### ISSUE THREAD

**Issue by skywalkerdude** [HymnalDreamTeam/Hymns-iOS#174]
Rare occasion, but still technically feasible:
![Simulator Screen Shot - iPhone 8 - 2020-05-22 at 00 28 20](https://user-images.githubusercontent.com/1427524/82642698-2df23f00-9bc3-11ea-8dd3-ba958e071626.png)

What would be a good experience to show the empty state?

**Comment by Emyeh** [comment]
@skywalkerdude If there's no song info we should just disable to the info icon and making at 25% opacity.

**Comment by Emyeh** [comment]
Actually since the buttons within the toolbar are dynamic we should just remove the info icon or option completely if there is none.

**Comment by skywalkerdude** [comment]
Repurposing task for removing the icon/option if there is no song info to show
