### ISSUE TITLE
Generic empty state for when web view fails to load

### ISSUE THREAD

**Issue by skywalkerdude** [HymnalDreamTeam/Hymns-iOS#175]
Web views may fail to load. Currently we only use it to show the privacy policy, but there could be other stuff in the future.

![Simulator Screen Shot - iPhone 8 - 2020-05-22 at 00 33 38](https://user-images.githubusercontent.com/1427524/82643204-fafc7b00-9bc3-11ea-870f-e74a9cd84143.png)

**Comment by Emyeh** [comment]
Would we be able to detect if it was a connection issue? @skywalkerdude

**Comment by skywalkerdude** [comment]
I don't think so, at least not right now that I know of

**Comment by Emyeh** [comment]
Added a generic error state for both iOS and Android: https://www.figma.com/file/7H5ApjzuVuJL3OP7FvE2qe/h-app?node-id=1418%3A6216
