### ISSUE TITLE
Create "About Us" page

### ISSUE THREAD

**Issue by Emyeh** [HymnalDreamTeam/Hymns-iOS#198]
Just a suggestion but what do you all think about including where these hymns are from? This would be for users who aren't from the Lord's Recovery. We don't have to explicitly call out hymnal.net, but a way to inform these users the origins of the hymns even the recovery version Bible?

Some ideas could be as simple as adding a short sentence in browse and have a 'learn more' that links to more info. We could also consider an about section in settings.

**Comment by skywalkerdude** [comment]
We'd have to create like a page somewhere then explaining things? What would would we put in that explanation?

**Comment by finben** [comment]
It may be good to have some about section in settings. I would just mention many hymns are sourced from hymnal.net or something as a reference. Idk... whatever you guys think here is fine with me.

**Comment by Emyeh** [comment]
An about page within settings sounds good. I was thinking it could mention how we're a small team who created this app to give free access to hymns. The hymns are from the local churches or hymnal.net and inspired by the Recovery version bible. Then potentially link to these places.

Not high priority but this information could also be included in the Google Play description.

**Comment by skywalkerdude** [comment]
Okay. Could someone build out what it should look like and what the text should say?

**Comment by Emyeh** [comment]
I'll take a stab first.

**Comment by Emyeh** [comment]
Tried out a first draft, feel free to edit or provide feedback. If this is too much work we can also just have it in the Google Play description.

![image](https://user-images.githubusercontent.com/26554065/84219315-118c4880-aa85-11ea-8453-348fc1d86a92.png)

**Comment by finben** [comment]
@skywalkerdude I can work on this if you want. Or do you want this to be a first issue for someone lol?

**Comment by skywalkerdude** [comment]
You can go ahead and do it

**Comment by skywalkerdude** [comment]
@finben FYI I tweaked the wording of the page in figma

**Comment by skywalkerdude** [comment]
@finben @Emyeh I made some tweaks/simplifications to the about us page. What do you think about this wording

<img width="493" alt="Screen Shot 2020-06-11 at 9 33 34 PM" src="https://user-images.githubusercontent.com/1427524/84465206-40442380-ac2b-11ea-9b01-a5332d69fca0.png">

**Comment by skywalkerdude** [comment]
Or we can hyperlink the entire verse. That's probably fine too. But I feel like this way is a little bit more subtle but still plugs BFA/Recovery version

**Comment by finben** [comment]
I like the wording changes and the linking of the entire verse. I don't think the (RcV) is necessary and can just be confusing to people since it's not a major version name like NIV that is recognizable, plus I don't think anyone would guess that it is a hyperlink.

Besides having the verse link personally, still like a little more of an explicit plug to BfA. I think the about us page is going to be something people would only glance at like one time quickly so if their isn't something explicit they will just never notice it. If we go forward with this wording maybe we can come up with something else to link them since "To learn more about this study Bible visit here" would no longer make sense. Anyways, those are just my two cents. Maybe @Emyeh can weigh in her thoughts.

**Comment by Emyeh** [comment]
This looks good to me. I agree we don't need the 'RcV', I don't think people will know what that stands for.

I think the reason for making the BfA plug less explicit is we're not sure if it's okay to associate it the app with it. If it is okay then it makes more sense to have a noticeable 'learn more' link.

**Comment by skywalkerdude** [comment]
Okay. Let's go with the new wording and for the learn more, we can put "Tap here for a free study Bible" or something like that. We are releasing to mostly saints in this first round anyway, and we can get their feedback.

**Comment by Emyeh** [comment]
Sounds good
