### ISSUE TITLE
Music player doesn't appear for french songs

### ISSUE THREAD

**Issue by skywalkerdude** [HymnalDreamTeam/Hymns-iOS#205]
Repro steps:
1) Search for 1151
2) Navigate to Hymn 1151
3) Navigate to French
4) Tap on the "play" button

Expected: either the play button isn't there, or the music appear should appear

**Comment by skywalkerdude** [comment]
@finben should this be closed?

**Comment by finben** [comment]
Closing as the further enhancement can be done to address #219
