### ISSUE TITLE
Open Question: Browse with null category/subcategory?

### ISSUE THREAD

**Issue by skywalkerdude** [HymnalDreamTeam/Hymns-iOS#211]
Some songs have null category and subcategory.

How should we display these songs in the browse section? On Android, we just kind of ignore them and don't show them. But we could have like a special "unknown" or "miscellaneous" section for these other hymns? The downside would be there might be a ton of orphaned hymns, and it'd look weird if a plurality or majority of hymns were in this misc category. WDYT, @finben @Emyeh 

(Applies too Android also)

**Comment by skywalkerdude** [comment]
ping @Emyeh @finben

**Comment by Emyeh** [comment]
I think it's better to still show them then not provide it at all, then it won't look like hymns are missing. We can call it 'All other'?

**Comment by skywalkerdude** [comment]
These are surfaced in "All Hymns", so I think we are good. We won't surface them in the categories section, and I think that makes sense. Closing as WAI
