### ISSUE TITLE
Add splash image/animation

### ISSUE THREAD

**Issue by skywalkerdude** [HymnalDreamTeam/Hymns-iOS#218]
I think this would be in the LaunchScreen.storyboard

Open questions:
Should we just use a static image, or should we use the delightful little animation that we have on Android?
Pros: it's more delightful to have the little animation than a static image
Cons: The animation takes like 1.5 seconds, so the user has to wait for 1.5 seconds to enter into the app each time.

On Android, we only show the animation when we need to (i.e. there's some background initialization work that needs to be done). Otherwise we go straight to the home page. Not sure if that is feasible to do on iOS though

Library to display the animation: https://github.com/airbnb/lottie-ios

**Comment by skywalkerdude** [comment]
@Emyeh could you share the splash file here with us again? I can't seem to find where you shared it last time 😞

**Comment by skywalkerdude** [comment]
screencast of animation on android: https://drive.google.com/file/d/1Ybz8o-cwEgDHf75MkE_93BW8ZMZ983D9/view?usp=sharing

**Comment by Emyeh** [comment]
The animation files are in this folder: https://drive.google.com/drive/folders/1b_MwTpoGfeRjX_1AURKMpBVQDpvYmNz7?usp=sharing

It's the html and json files. The html is just a demo of what it looks like.

**Comment by skywalkerdude** [comment]
Hmm, it looks like we can't make it animate on iOS, as per https://github.com/HymnalDreamTeam/Hymns-iOS/pull/221#issue-425523001.

@Emyeh could you create just a static page we could use as the splash screen instead?

**Comment by Emyeh** [comment]
Added a static splash page on ios figma. The background, logo, and text are separated.

**Comment by finben** [comment]
@Emyeh Is it possible to download the image as a png file without a background? It seems like I can't do that since I have view only mode on Figma maybe?

**Comment by finben** [comment]
My problem is the background with it is white and its not working for dark mode. Also, which element should I export? So far I had exported # Splash but then needed to crop it to a square. Obviously, this probably isn't ideal or what you have in mind for me to do lol

**Comment by Emyeh** [comment]
I organized the layers on Figma ios page so that each piece on the splash image could be exported separately. To make it easier I've exported each layer as an svg and png (includes light and dark mode): https://drive.google.com/drive/folders/1g7zFd9tIxg1EY4a-5B6O9QftOmqZDMPg?usp=sharing

Let me know if you need it at a different size or file type.

**Comment by finben** [comment]
Added in recent commit
