### ISSUE TITLE
Navigating back to the home screen always goes to the home tab

### ISSUE THREAD

**Issue by skywalkerdude** [HymnalDreamTeam/Hymns-iOS#231]
@finben it looks like you added this PR: https://github.com/HymnalDreamTeam/Hymns-iOS/pull/118

Do you remember what the issue that this fix is for? I've found that it breaks navigation because of
```
            }.onAppear {
                self.selectedTab = .home
            }
```

So when you navigate back from any other screen, the `onAppear` will force it to go back to the home tab instead of the tab you were previously on

**Comment by skywalkerdude** [comment]
See video:

[video-1590038334.mp4.zip](https://github.com/HymnalDreamTeam/Hymns-iOS/files/4719492/video-1590038334.mp4.zip)

**Comment by finben** [comment]
Yeah, the problem is this is a fix for that first icon being lower than the others. 
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-06-05 at 10 48 26](https://user-images.githubusercontent.com/15247726/83896697-2d58bd00-a71a-11ea-911d-47818a99dad6.png)
