### ISSUE TITLE
Designs for tags

### ISSUE THREAD

**Issue by finben** [HymnalDreamTeam/Hymns-iOS#238]
@Emyeh When you get the chance could you provide some designs for tagging hymns. Right now I have this coded up but I am sure this is not what we want lol 
![Simulator Screen Shot - iPhone 11 - 2020-06-04 at 12 33 06](https://user-images.githubusercontent.com/15247726/83791790-d393bc80-a65f-11ea-9fb2-3e906da35bbe.png)

**Comment by Emyeh** [comment]
You guys are too fast hahah. I'll work on the design for this.

**Comment by Emyeh** [comment]
Updated design for tag ios: 
https://www.figma.com/file/7H5ApjzuVuJL3OP7FvE2qe/h-app?node-id=647%3A3155

Let me know if you have any questions.

**Comment by Emyeh** [comment]
Updated the iOS design for multiple tags. Let me know what you think. Here is the prototype for how the interaction works adding and removing a tag: https://www.figma.com/proto/7H5ApjzuVuJL3OP7FvE2qe/h-app?node-id=1468%3A1028&scaling=min-zoom

**Comment by finben** [comment]
Look great!! Conversation is mostly resolved and moved to #257
