### ISSUE TITLE
Design for empty tags state

### ISSUE THREAD

**Issue by skywalkerdude** [HymnalDreamTeam/Hymns-iOS#245]
Need for iOS and Android. Since we have that little image for search and favorites, would it be good to have one for when tags are empty, just to match the other cases?

Currently empty tags looks like this:
![Screenshot_1591394553](https://user-images.githubusercontent.com/1427524/83926067-a3225000-a73d-11ea-9650-98339901e2af.png)

**Comment by Emyeh** [comment]
Yeah it would be nicer to have a illustrative empty state here too. Will make one.

**Comment by Emyeh** [comment]
Empty tag state added for ios and android: https://www.figma.com/file/7H5ApjzuVuJL3OP7FvE2qe/h-app?node-id=647%3A3155

Android is at 200dp but iOS isn't. Does it need to be within 200x200 for iOS?

**Comment by skywalkerdude** [comment]
Assigning to @finben to implement, since he is working on the tags view!

**Comment by finben** [comment]
Done
