### ISSUE TITLE
Can't find the hymn 'But you, beloved'

### ISSUE THREAD

**Issue by Emyeh** [HymnalDreamTeam/Hymns-iOS#247]
![IMG_7532](https://user-images.githubusercontent.com/26554065/83930837-788cc300-a74e-11ea-9f8f-43179800750a.PNG)

**Comment by skywalkerdude** [comment]
@Emyeh can you file feedback to hymnal.net(https://www.hymnal.net/en/contactus) to fix the title of https://www.hymnal.net/en/hymn/ns/537
