### ISSUE TITLE
Create a send feedback button

### ISSUE THREAD

**Issue by skywalkerdude** [HymnalDreamTeam/Hymns-iOS#252]
In settings, like in Android, have a send feedback button.

Email should be sent to: hymnalappfeedback@gmail.com
with the subject: Hymnal App Feedback # {RANDOM_NUMBER}

**Comment by finben** [comment]
Should I make the subject: Hymnal iOS App Feedback? So you can differentiate between these and the ones coming from your android app?

**Comment by skywalkerdude** [comment]
> Should I make the subject: Hymnal iOS App Feedback? So you can differentiate between these and the ones coming from your android app?

Yup, that sounds good to me! I'll change the Android one to say "Android".
