### ISSUE TITLE
Implement PDF error state

### ISSUE THREAD

**Issue by skywalkerdude** [HymnalDreamTeam/Hymns-iOS#254]
Related to https://github.com/HymnalDreamTeam/Hymns-iOS/issues/228.

We need to show the generic error state (added in https://github.com/HymnalDreamTeam/Hymns-iOS/pull/253) when a PDF fails to load for an unknown reason.

Note: If possible, please do not merely copy what I did for the web view. That only checks if the url is invalid or not. This is okay for webviews because if the url is valid but doesn't point to anything, the WebView will show a 404 page, which is an error screen in and of itself. Pdf viewer has no such functionality. If the url is valid but the pdf viewer fails to render, then it'll still just show a blank page. Therefore, we need to DETECT when a pdf fails to load and show the error view, so it is a little bit more involved than merely checking the url's validity.

**Comment by Emyeh** [comment]
If the music sheet is not available can we remove the tab?

**Comment by skywalkerdude** [comment]
@Emyeh it's not that the sheet music is not available. It's that there is a url, but the url doesn't load for some reason. We won't be able to hide it in that case because we won't know that the url is wrong at the time of rendering the tabs.

**Comment by Emyeh** [comment]
[Error.pdf](https://github.com/HymnalDreamTeam/Hymns-iOS/files/4762374/Error.pdf)

Attached a pdf export

**Comment by finben** [comment]
Done! Thanks @Emyeh
