### ISSUE TITLE
Tags Having Multiple Tags

### ISSUE THREAD

**Issue by finben** [HymnalDreamTeam/Hymns-iOS#257]
Hey Emily! Thanks for making the tags. They look awesome!! One question I had is I can't tell from the Figma what it would look like if you want to have multiple tags on a single song. For instance in this view. I don't have the option to just create another tag but can only delete the existing. 

![image](https://user-images.githubusercontent.com/15247726/83982875-a8270100-a8ef-11ea-9f0e-63b5b61731ae.png)

Also, in this one I don't really get the workflow with the + button. Does that just signify you are done typing and then you still need to click the "save" button? on the other view. It's wierd to me because what if halfway through typing you realizing you want to backout and not have one. You are stuck first clicking the + button to get out of that view and then hitting cancel instead of save? Hopefully, that makes sense? 

![image](https://user-images.githubusercontent.com/15247726/83982972-4c10ac80-a8f0-11ea-8e43-8fba4c5ec3fc.png)

**Comment by Emyeh** [comment]
Sorry that's a mock error, it should have a cancel & save at the bottom even when typing. I'll fix that. I wasn't sure if we wanted to allow for multiple tags. They way I have it now for ios is allowing only one.

There are valid use cases to having multiple. If we're able build it then I'll rethink the design a bit.

**Comment by finben** [comment]
Yes, we can build it, actually have already built the backend to store multiple tags for any hymn so I think it will be very easy for us to support.

**Comment by Emyeh** [comment]
Added the the designs for multiple tags on #238

**Comment by finben** [comment]
Thank you! One more thing lol... What do we display on our TagList if a user selects the same tag name but different color when they input a tag for two different songs. I think this picture assumes that every time they put in a small group tag they are also clicking yellow as their color. But what if that is not the case?


![Parent Child Toolbar_ Child View 1 - Light](https://user-images.githubusercontent.com/15247726/84399750-d42fd400-abc6-11ea-811f-2cc1cbd998b0.png)

**Comment by finben** [comment]
I am getting close to having this implemented and it is looking great! one small tweak I wanted to ask about is the default tag foreground red color. To me it looks a bit bright and almost seems like the tag is selected when it has not been selected yet. I am wondering if we can make it slightly more mellow to blend in more when it is not selected.  

![Simulator Screen Shot - iPhone 8 - 2020-06-11 at 14 48 23](https://user-images.githubusercontent.com/15247726/84432759-e6276c00-abf2-11ea-840f-cbdea492ca1f.png)

**Comment by Emyeh** [comment]
Make sense I'll adjust the tone of the red pill. 

For you other question I think you bring up a good use case. For what we have now we would show the same pill in different colors as separate. There's a possibility the user may have the same title, but chose a different color to keep it different. There's a bigger chance though that they might've forgotten what color they chose for that label. It makes me think it's probably useful to provide users a way to add tags that have already been created.

Let me try a V2 with this in mind.

**Comment by Emyeh** [comment]
Okay I just realized you're asking about the defaults colors we would show in the tag list hahah. The mock I have is just an example, it doesn't auto assign or lock down a different color for the label. It should only reflect the color and text the user has created.

**Comment by Emyeh** [comment]
Adjusted the red pill:
Text - **EA4D85**
Bk - **EA4D85 at 20% opacity**

@finben

**Comment by skywalkerdude** [comment]
@finben can we close this issue?

**Comment by finben** [comment]
Yeah, I have a PR open for the thing that closes it so just approve that.
