### ISSUE TITLE
About us page's bfa link should link to external browser

### ISSUE THREAD

**Issue by skywalkerdude** [HymnalDreamTeam/Hymns-iOS#282]
I think in this case, it's probably better to link to an external browser with better navigation support than to use a webview, since we want them to go through the site and order a bible.

Currently, this is a little hard to navigate:
![Simulator Screen Shot - iPhone 8 - 2020-06-12 at 23 06 58](https://user-images.githubusercontent.com/1427524/84561459-7227b980-ad01-11ea-91e8-f4ff2407f58c.png)

**Comment by finben** [comment]
Can we put analytics on this link to see how many people actually go to their website. I think it would be interesting to see

**Comment by skywalkerdude** [comment]
Sure, that sounds fine. Can you add it? I'm afk right now
