### ISSUE TITLE
Font size switching animation not smooth

### ISSUE THREAD

**Issue by Emyeh** [HymnalDreamTeam/Hymns-iOS#292]
I like the idea watching it shrinking and grow but when that happens you can see a lot of '...' cutting off text.
![IMG_7556](https://user-images.githubusercontent.com/26554065/84587385-9fdd3300-add3-11ea-959d-cd2198e690e7.PNG)

**Comment by skywalkerdude** [comment]
Hmm, it doesn't seem to resize correctly either. It seems to look like this after resizing from extra large back to normal:
![Simulator Screen Shot - iPhone 8 - 2020-06-14 at 13 48 26](https://user-images.githubusercontent.com/1427524/84603776-e66b7580-ae45-11ea-8bc5-28e65e4ae700.png)

**Comment by skywalkerdude** [comment]
(should be left-aligned). @finben can you take a look
