### ISSUE TITLE
Dynamic type bug: Can't see what I'm searching

### ISSUE THREAD

**Issue by Emyeh** [HymnalDreamTeam/Hymns-iOS#309]
![IMG_7572](https://user-images.githubusercontent.com/26554065/84722821-28c1af00-af39-11ea-8b40-8ee7c95ac445.PNG)

The current suggestion for an accessible dynamic type experience is to keep buttons the same size. The 'Cancel' takes up half the space here which make search inaccessible. I would say this is a blocker because search is our main feature.

Here is an example of what Chrome does on iOS
![IMG_7573](https://user-images.githubusercontent.com/26554065/84723066-9d94e900-af39-11ea-822e-a7932a321aa2.PNG)

**Comment by Emyeh** [comment]
@finben Hey Ben would you be able to help with this bug, #310, and #316 ? They're not open Beta Blockers, but definitely an issue for full public use. I'm only pushing for this because there are lot of saints who increase overall type size of their phone, and these issues potentially block key use cases. 

The example I have is the most extreme but if we can adjust the layout here it'll work for any size. The biggest fix for most of these dynamic type bugs is just making sure CTAs don't scale, which is the current industry recommendation. 

Let me know what you think!

**Comment by finben** [comment]
Wow! That is great to hear that we just keep buttons from changing size. I think that will make alot of these changes easier for Luke and I both. Yeah, I'll take a look

**Comment by Emyeh** [comment]
Thank you!!

**Comment by finben** [comment]
#328 Addresses. How does this look? 
![Simulator Screen Shot - iPhone 8 - 2020-06-18 at 13 10 41](https://user-images.githubusercontent.com/15247726/85058567-e92cda00-b167-11ea-950f-1f3bae484d4c.png)

**Comment by Emyeh** [comment]
This looks a lot better! Typically text CTAs are also kept the same size as well, but I think we're okay with what we have now. I do think text CTAs need to be treated differently vs icons. The goal here is to make sure I can still see a good amount of what I'm typing in search.
