### ISSUE TITLE
Dynamic type bug: Song info is truncated

### ISSUE THREAD

**Issue by Emyeh** [HymnalDreamTeam/Hymns-iOS#310]
![IMG_7571](https://user-images.githubusercontent.com/26554065/84723200-e77dcf00-af39-11ea-8745-d489594f097e.PNG)

Typically when font size is enlarged, unless it was truncated to begin with it shouldn't truncate. Right now I can't read much about the info because of it. It seems like this happens when the titles and info are within its own sections side by side. 

Here an example of what I'm suggesting (added on Figma): 
![image](https://user-images.githubusercontent.com/26554065/84724258-928f8800-af3c-11ea-8aa1-61b24c5e1332.png)

We can separate the titles vertically so it can wrap nicely. The popup would need to be scrollable.

**Comment by skywalkerdude** [comment]
Need an alternate layout here: https://developer.apple.com/videos/play/wwdc2017/245/ (Minute 15)

**Comment by finben** [comment]
Addressed
