### ISSUE TITLE
Dynamic type bug: Color choice pills not readable

### ISSUE THREAD

**Issue by Emyeh** [HymnalDreamTeam/Hymns-iOS#312]
![IMG_7569](https://user-images.githubusercontent.com/26554065/84724746-c5864b80-af3d-11ea-946e-a5ed50ad5fe2.PNG)

We can either stack the pills or make them horizontally scrollable.

**Comment by finben** [comment]
![Simulator Screen Shot - iPhone 11 Pro - 2020-06-29 at 10 15 50](https://user-images.githubusercontent.com/15247726/86023639-89e58a00-b9f1-11ea-849c-ec9a099765e7.png)
Issue addressed
