### ISSUE TITLE
Dynamic type bug: Audio player buttons are cutting off at the sides

### ISSUE THREAD

**Issue by Emyeh** [HymnalDreamTeam/Hymns-iOS#313]
![IMG_7568](https://user-images.githubusercontent.com/26554065/84724897-26ae1f00-af3e-11ea-81a7-88fe62f1a97d.PNG)

We can maintain the button size when font scales up.

**Comment by finben** [comment]
![Simulator Screen Shot - iPhone 11 Pro - 2020-06-29 at 10 16 28](https://user-images.githubusercontent.com/15247726/86023719-a255a480-b9f1-11ea-9517-4f6ba8671ff0.png)

Issue addressed
