### ISSUE TITLE
Dynamic type: About us mostly truncated

### ISSUE THREAD

**Issue by Emyeh** [HymnalDreamTeam/Hymns-iOS#314]
![IMG_7567](https://user-images.githubusercontent.com/26554065/84725010-74c32280-af3e-11ea-9ca3-9f78755505c9.PNG)

**Comment by finben** [comment]
@skywalkerdude We need to do an alternative layout here for sure. https://developer.apple.com/videos/play/wwdc2017/245/  minute 15

**Comment by skywalkerdude** [comment]
I just put everything in a scrollview, which seems to handle it pretty well
