### ISSUE TITLE
Hymns titles in under Scripture in Browse aren't aligned

### ISSUE THREAD

**Issue by Emyeh** [HymnalDreamTeam/Hymns-iOS#321]
I see that the verse number is aligned but the hymn title alignment starts to look funny. Can we give a max length for the numbers and align the hymn titles with 16dp padding between?

IMG_7581

**Comment by skywalkerdude** [comment]
@Emyeh I don't see the screenshot you posted?

**Comment by skywalkerdude** [comment]
oh, I see. This happens because the verse reference takes a different amount of space. How do you think we should align it? What if the verse reference is too long?

**Comment by Emyeh** [comment]
We can try something like this 
![image](https://user-images.githubusercontent.com/26554065/86565363-8a63b080-bf1c-11ea-99fd-0aa977c8a26b.png)

- Keep the verse # the same text size and left align it with the book title
- Add 16dp padding between the verse number and hymn title
- Remove the left caret for more space on the left
