### ISSUE TITLE
Dynamic type bug: Hymn title cut off at the bottom

### ISSUE THREAD

**Issue by Emyeh** [HymnalDreamTeam/Hymns-iOS#323]
![IMG_7568](https://user-images.githubusercontent.com/26554065/84860523-08225380-b024-11ea-9fc3-606ee5bd32bb.PNG)

**Comment by finben** [comment]
#328 addresses
![Simulator Screen Shot - iPhone 8 - 2020-06-18 at 13 21 57](https://user-images.githubusercontent.com/15247726/85058400-b1be2d80-b167-11ea-99b9-101f2f5ef157.png)
