### ISSUE TITLE
Dynamic type bug: Tabs are cut off at the bottom

### ISSUE THREAD

**Issue by Emyeh** [HymnalDreamTeam/Hymns-iOS#324]
![IMG_7568](https://user-images.githubusercontent.com/26554065/84860551-15d7d900-b024-11ea-8536-f3fcb1ec3ddf.PNG)

**Comment by finben** [comment]
#328 addresses this 
![Simulator Screen Shot - iPhone 8 - 2020-06-18 at 13 21 57](https://user-images.githubusercontent.com/15247726/85058343-994e1300-b167-11ea-8b0f-dcc453a31572.png)
