### ISSUE TITLE
Navigation Links only work once

### ISSUE THREAD

**Issue by finben** [HymnalDreamTeam/Hymns-iOS#34]
I have read that this is an xcode simulator bug only and does not effect real devices. However, we should still mark this as an issue until someone has the chance to text this on a real device. When you go into a detailed hymn view and come back navigation works but if you try to click the same hymn again to see the details it does not work the second time. Maybe someone can eventually test this on a real device then we can resolve this issue.

**Comment by skywalkerdude** [comment]
Yeah this happens to me too... haha. @finben Does Johnanna have a real iPhone? :P

**Comment by finben** [comment]
Lol! yeah, I'll look into putting the app on her iPhone

**Comment by finben** [comment]
Confirmed that this issue does not take place on actual devices
