### ISSUE TITLE
Back caret hard to tap

### ISSUE THREAD

**Issue by Emyeh** [HymnalDreamTeam/Hymns-iOS#378]
![IMG_7710](https://user-images.githubusercontent.com/26554065/86980284-4fd65f80-c138-11ea-8b79-3a3e71b598d8.PNG)

I've run into this issue a lot. My finger is small but it takes me several taps to go back. Not sure if the tap target isn't 48x48dp or it's a bug with the caret itself.

**Comment by skywalkerdude** [comment]
Yeah, I've run into this also. It is certainly quite the annoyance. @finben could you see if you can make the touch target larger?
