### ISSUE TITLE
Getting native translators

### ISSUE THREAD

**Issue by finben** [HymnalDreamTeam/Hymns-iOS#387]
[AppStrings.txt](https://github.com/HymnalDreamTeam/Hymns-iOS/files/4956540/AppStrings.txt)

@skywalkerdude Here is a list of all the extracted strings from our app. I exported the xliff for localization and then removed all of the preview strings and stuff I found. This should be an inclusive list of all the user facing strings in our app. 

One thing I want to mention is I think we are better getting native translators for German and Spanish. I could make an attempt but your never know when something just won't look write to native speakers. I was thinking of reaching out to Jonathen Gil (do you know him?) and having him translate the German. Maybe we could do the same with the Spanish or any other languages we want to support. We just send them this text file and ask them to send it back to us translated. Was denkst du? (What do you think?)

**Comment by skywalkerdude** [comment]
ohh okay. I thought you were a native Spanish speaker, haha (and more or less a native German speaker now too) 😛

Which do you think you're better at? Could you just localize the language you're better at (just so we can try it in that language and make sure it works technically, and that we aren't missing some strings), then we can ask him to play around and see if anything doesn't make sense?

**Comment by finben** [comment]
That's a good idea. I can just do both and we will have people proof read it later
