### ISSUE TITLE
Create custom SF Symbols 

### ISSUE THREAD

**Issue by finben** [HymnalDreamTeam/Hymns-iOS#419]
For the youtube and soundcloud custom buttons on Figma, we are going to need them to meet the SF symbol format so that they will scale and stay uniform with our other symbols. I tried to edit them in Sketch but I am not very familiar with it :/ 

Would you be willing to take a look at conforming the SVG icons from Figma to meet the SF symbols specifications? Here are two resources I found on the topic. 

https://developer.apple.com/documentation/uikit/uiimage/creating_custom_symbol_images_for_your_app
https://developer.apple.com/videos/play/wwdc2019/206/

**Comment by Emyeh** [comment]
Created and reviewed custom SF Symbols for SoundCloud and Youtube
