### ISSUE TITLE
Add a close/dismiss button on privacy policy

### ISSUE THREAD

**Issue by skywalkerdude** [HymnalDreamTeam/Hymns-iOS#428]

**Comment by finben** [comment]
Should we get a spec from Emily for this? Probably, should do something consistent across all of our webViews. 

Also, should we leave it as a sheet?

**Comment by skywalkerdude** [comment]
Sure, if you want to ask her. But I think if we just put a close button the top, that's sufficient. Don't really need super detailed mocks for this @finben
