### ISSUE TITLE
Soundcloud icon not vertically centered

### ISSUE THREAD

**Issue by Emyeh** [HymnalDreamTeam/Hymns-iOS#445]
![image](https://user-images.githubusercontent.com/26554065/89945085-a6bad300-dbd5-11ea-816c-0a6250608515.png)

**Comment by skywalkerdude** [comment]
So the soundcloud banner is technically centered, because there's padding in the tab bar:

<img width="330" alt="Screen Shot 2020-08-11 at 2 40 45 PM" src="https://user-images.githubusercontent.com/1427524/89951655-aa078c00-dbe0-11ea-99ff-59a3f60af55b.png">

**Comment by skywalkerdude** [comment]
Removed the bottom padding on the sound cloud mini player thing and kept the padding on the actual button bar
![Screen Shot 2020-08-11 at 2 46 58 PM](https://user-images.githubusercontent.com/1427524/89953900-dde4b080-dbe4-11ea-807b-64ec361ff127.png)

**Comment by Emyeh** [comment]
Edited the icon:
https://drive.google.com/file/d/1UTswdg7rf7iDdXTMwDSD9uqG4dcykf7n/view?usp=sharing
