### ISSUE TITLE
Search Bar immediately pops on actual device

### ISSUE THREAD

**Issue by finben** [HymnalDreamTeam/Hymns-iOS#88]
On real device as soon as the app the animation takes place where the search bar goes up. Also, it goes higher than the screen so you can't select it....

**Comment by skywalkerdude** [comment]
can you elaborate what you mean? "On real device as soon as the app the animation takes place where the search bar goes up" is not valid sentence 😛

**Comment by finben** [comment]
Lol, When I open the app. Immediately the search bar animation takes places on the home view. From that point onwards the search bar is unreachable and above the top of the screen space.

**Comment by finben** [comment]
This issue actually gets fixed in my latest PR which addresses the ignoring safe edges.
